# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

from collections import Counter
def findTheDifference(s, t):
    count_s = Counter(s)
    count_t = Counter(t)

    for ch in count_t:
        if count_t[ch] > count_s.get(ch, 0):
            return ch
